# Generated by Django 4.2.3 on 2023-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.AddField(
            model_name='productdata',
            name='images',
            field=models.ManyToManyField(blank=True, to='app.productimage'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka Division', 'Dhaka Division'), ('Chattogram Division', 'Chattogram Division'), ('Khulna Division', 'Khulna Division'), ('Barishal Division', 'Barishal Division'), ('Sylhet Division', 'Sylhet Division'), ('Rangpur Division', 'Rangpur Division'), ('Mymensingh Division', 'Mymensingh Division')], max_length=50),
        ),
    ]
